all:
	javac -cp "lib/*:."  -d class server/fileencryption/*.java server/goodthoughts/*.java server/passwordgenerator/*.java server/filetransfer/*.java server/internetsearch/*.java server/Server.java server/ThreadServer.java server/currencyconverter/*.java	

run:
	java -cp "lib/*:class" server.Server

doc:
	javadoc -d doc -cp "lib/*:." server/fileencryption/*.java server/goodthoughts/*.java server/passwordgenerator/*.java server/filetransfer/*.java server/internetsearch/*.java server/Server.java server/ThreadServer.java server/currencyconverter/*.java

